# Generated by Django 2.2.2 on 2019-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_image_url_blank_true'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='event',
            new_name='events',
        ),
    ]
